urdf clean up
boardwalkrobotics/alex-robot-models pull request #1
Opened 2024-08-09 22:52 UTC by khizarmohammed1997

2024-08-13 14:58 UTC, christiandebuys requested changes

2024-08-13 14:58 UTC, christiandebuys commented on alex_description/urdf/20240808_Alex_WithSpine_Nubs.urdf
I would remove "WithSpine". The default should be that the robot has all its joints, and we say what it's missing in the urdf and enum names.

2024-08-13 14:58 UTC, christiandebuys commented on alex_description/urdf/20240808_Alex_Spineless_BarrettHands.urdf
Really just an opinion, but "Spineless" sounds silly to me. Maybe "NoSpine", "NoHands", etc. Just "No[ThingThatIsMissing]"

2024-08-13 14:58 UTC, christiandebuys commented on alex_description/meshes_backup/Torso_Updated.obj
What is "updated" here? If these are the new files, I would rename Torso.mtl and Torso.obj to "_old" and maybe move them somewhere else. Then you can call the updated ones just "Torso".

2024-08-13 14:58 UTC, christiandebuys commented on alex_description/urdf/20240808_Alex_Spineless_BarrettHands.urdf
The Barrett file has the dumbbells in the urdf, but that is not reflected in the enum name. Should have "WithDumbbells" and could probably just make it a separate urdf.

2024-08-13 14:58 UTC, christiandebuys commented on alex_description/urdf/20240808_Alex_WithSpine_Nubs.urdf
Also this guy seems to have some issues:
![image](https://github.com/user-attachments/assets/ab0d9266-41b8-4005-ab87-fa257bb61b4c)

2024-08-14 19:12 UTC, khizarmohammed1997 commented on alex_description/urdf/20240808_Alex_WithSpine_Nubs.urdf
As discussed, with spine URDF will not be accurate at all

2024-08-14 19:12 UTC, khizarmohammed1997 commented on alex_description/urdf/20240808_Alex_Spineless_BarrettHands.urdf
Fixed these

2024-08-14 19:15 UTC, khizarmohammed1997 commented on alex_description/meshes_backup/Torso_Updated.obj
Removed them

2024-08-14 19:23 UTC, christiandebuys approved these changes

2024-08-14 21:19 UTC, merged