Flat hands urdf
boardwalkrobotics/alex-robot-models pull request #2
Opened 2024-08-20 19:46 UTC by christiandebuys

2024-08-27 18:07 UTC, achintyamohan requested changes

2024-08-27 18:07 UTC, achintyamohan commented on alex_description/urdf/20240819_Alex_FixedSpine_FlatHands.urdf
> +            <inertia ixx="4.97311e-4" ixy="2.793e-5" ixz="-1.15e-7" iyy="3.66606e-4" iyz="1.3979e-5" izz="2.53076e-4" />
Can these be reverted back to the original values? Would be nice to have something close to realistic. Alternatively, we can also look at simplified geometry

2024-08-28 20:07 UTC, christiandebuys commented on alex_description/urdf/20240819_Alex_FixedSpine_FlatHands.urdf
> +            <inertia ixx="4.97311e-4" ixy="2.793e-5" ixz="-1.15e-7" iyy="3.66606e-4" iyz="1.3979e-5" izz="2.53076e-4" />
done

2024-08-28 22:18 UTC, achintyamohan approved these changes

2024-08-28 22:34 UTC, merged