URDF Cleanup
boardwalkrobotics/alex-robot-models pull request #5
Opened 2024-10-24 22:39 UTC by christiandebuys

2024-10-30 19:11 UTC, bshrewsbury commented on barrett_description/urdf/BarrettHands_WithDumbbells.urdf
> +	<joint name="LeftGrippertAttachmentFixedJoint" type="fixed">
Can we move the extra weight into the barrett hand urdf as a fixed joint and link, but commented out and delete this extra URDF?

2024-10-30 19:13 UTC, bshrewsbury commented on alex_description/urdf_backup/20240808_Alex_FixedSpine_SakeHands.urdf
Can we remove this? Fixed spine nubs is enough

2024-10-30 19:14 UTC, bshrewsbury approved these changes

2024-10-30 19:23 UTC, achintyamohan requested changes

2024-10-30 19:23 UTC, achintyamohan commented on ability_hand_description/urdf/PsyonicHands.urdf
> +<robot name="Alex">
Should the robot names for the hand urdfs still be Alex? I feel like we should name them PsyonicHand or something along those lines

2024-10-30 19:23 UTC, achintyamohan commented on barrett_description/urdf/BarrettHands_WithDumbbells.urdf
> +<robot name="Alex">
Same as Psyonic, should the root element still be Alex?

2024-10-30 19:23 UTC, achintyamohan commented on flat_hand_description/urdf/FlatHands.urdf
> +<robot name="Alex">
Same as the other two, should this still be named Alex?

2024-10-30 19:53 UTC, bshrewsbury commented on ability_hand_description/urdf/PsyonicHands.urdf
> +<robot name="Alex">
I think it should still be alex, I think this is the name that is used in yovariables, ros topics, all kinds of unexpected places

2024-10-30 22:24 UTC, bshrewsbury approved these changes

2024-10-30 22:26 UTC, dhruvthanki approved these changes

2024-10-31 00:20 UTC, christiandebuys commented on ability_hand_description/urdf/PsyonicHands.urdf
> +<robot name="Alex">
These urdfs are just to keep track of the hands and how they are intended to mount (gripper fixed joints). If we delete all urdfs with a certain hand, someone could still refer to these to see how the hands can be included in a urdf.

2024-10-31 00:23 UTC, achintyamohan approved these changes

2024-10-31 00:23 UTC, achintyamohan commented on ability_hand_description/urdf/PsyonicHands.urdf
> +<robot name="Alex">
okay, I doubt it matters that much.

2024-10-31 00:31 UTC, merged